language: java

dist: trusty

git:
  depth: 1 # an optimization since we won't be committing anything

stages:
- test
- deploy

jobs:
  include:

  - stage: test

    before_install:
    - source .travisci/setup.sh
    - sh .travisci/run_tests.sh


  - stage: deploy
    # require the branch name to be master (note for PRs this is the base branch name)
    if: |
      repo = javalite/activeweb AND \
      ( branch = master OR branch = java8 )

    before_install:
    - source .travisci/setup.sh
    script: sh $TRAVIS_BUILD_DIR/.travisci/deploy.sh